  gazebo_ros_control:
    pid_gains:
      iiwa_joint_1: 
        p: 100.0
        i: 0.01
        d: 10.0
        
      iiwa_joint_2: 
        p: 100.0
        i: 0.01
        d: 10.0
        
      iiwa_joint_3: 
        p: 100.0
        i: 0.01
        d: 10.0
        
      iiwa_joint_4: 
        p: 100.0
        i: 0.01
        d: 10.0
        
      iiwa_joint_5: 
        p: 100.0
        i: 0.01
        d: 10.0
        
      iiwa_joint_6: 
        p: 100.0
        i: 0.01
        d: 10.0   
        
      iiwa_joint_7: 
        p: 100.0
        i: 0.01
        d: 10.0        